### ISSUE TITLE
Proto3 syntax

### ISSUE THREAD

**Issue by TruDan** [mreu/ProtobufLanguageService#1]
Is it possible to get support for protobuf3 syntax? Things like "required" and "optional" are not actually required in proto3.

One way to detect would be `syntax = "proto3";`

**Comment by jordanbtucker** [comment]
:+1:

**Comment by mreu** [comment]
As long as proto3 is beta I have no plan to change the VS extension. I am still working on it and I will publish it when proto3 is final.

**Comment by mreu** [comment]
First support of proto3 in version 1.8.0
