### ISSUE TITLE
map shows red squiggles on proto3

### ISSUE THREAD

**Issue by paulburlumi** [mreu/ProtobufLanguageService#4]
Tested using:

> Microsoft Windows 7 Enterprise Service Pack 1
> 
> Microsoft Visual Studio Enterprise 2015
> Version 14.0.25431.01 Update 3
> 
> Protobuf Language Service
> Version 1.8.2

Opening the following .proto file I get many red squiggles on the map line

```
syntax = "proto3";

package p;

message m {
  map<string, string> broken = 1;
}
```

**Comment by mreu** [comment]
Fixed in version 1.9.0
