### ISSUE TITLE
Latest update has broken the dark theme highlighting

### ISSUE THREAD

**Issue by eberanek** [mreu/ProtobufLanguageService#6]
After updating to the latest, the protobuf keywords are highlighted with a white background when the dark VS theme is selected. I'm seeing this in VS2013.

**Comment by mreu** [comment]
Hi,
sorry I cannot reproduce this behaviour. It works for me in VS2013. You can edit all colors in VS2013 in Tools/Options/Fonts and Colors. All names of the colors starts with "Protobuf".
I hope this helps.

**Comment by eberanek** [comment]
Hello, thanks for pointing out the colors. I had not changed them myself, but I was able to change them to the same background as the dark theme. The strange thing was "Default" showed a white background, even though I was on the Dark Theme. Thanks again for having a look.
